{% set name = "ghapi" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ghapi-{{ version }}.tar.gz
  sha256: 9e7632c762d6f9c288e3b046b2d58c2f7992dda7c925683df435440912b10625

build:
  entry_points:
    - ghapi=ghapi.cli:ghapi
    - ghpath=ghapi.cli:ghpath
    - ghraw=ghapi.cli:ghraw
    - completion-ghapi=ghapi.cli:completion_ghapi
    - gh-create-workflow=ghapi.actions:gh_create_workflow
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fastcore
    - packaging
    - pip
    - python >=3.6

test:
  imports:
    - ghapi
  commands:
    - pip check
    - ghapi --help
    - ghpath --help
    - ghraw --help
    - completion-ghapi --help
    - gh-create-workflow --help
  requires:
    - pip

about:
  home: https://github.com/fastai/ghapi/
  summary: A python client for the GitHub API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - thewchan
