{% set name = "ghapi" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ghapi-{{ version }}.tar.gz
  sha256: 64fdd9f06d8e3373065c42c2a03e067e2bbb9ca18b583cd6e38a28aaad0224f6

build:
  entry_points:
    - ghapi=ghapi.cli:ghapi
    - ghpath=ghapi.cli:ghpath
    - ghraw=ghapi.cli:ghraw
    - completion-ghapi=ghapi.cli:completion_ghapi
    - gh-create-workflow=ghapi.actions:gh_create_workflow
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - fastcore >=1.7.2
    - packaging
    - pip
    - python >={{ python_min }}

test:
  imports:
    - ghapi
  commands:
    - pip check
    - ghapi --help
    - ghpath --help
    - ghraw --help
    - completion-ghapi --help
    - gh-create-workflow --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fastai/ghapi/
  summary: A python client for the GitHub API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - thewchan
