schema_version: 1

context:
  name: ghapi
  version: "2.0.5"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ghapi-${{ version }}.tar.gz
  sha256: 51fe5c4f51f68de322755948823ce8f3b7218363bd9f54f726e6cd56b12444c0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - ghapi=ghapi.cli:ghapi
      - ghpath=ghapi.cli:ghpath
      - ghraw=ghapi.cli:ghraw
      - completion-ghapi=ghapi.cli:completion_ghapi
      - gh-create-workflow=ghapi.actions:gh_create_workflow

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=64
  run:
    - python >=${{ python_min }}
    - fastcore >=2.1.16
    - fastspec >=0.1.2
    - pip

tests:
  - python:
      imports:
        - ghapi
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - ghapi --help
      - ghpath --help
      - ghraw --help
      - completion-ghapi --help
      - gh-create-workflow --help

about:
  summary: A python client for the GitHub API
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/fastai/ghapi/

extra:
  recipe-maintainers:
    - jtpio
    - thewchan
